cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart'),
    path('wishlist/', views.wishlist_detail, name='wishlist'),
    path('update_cart/', views.update_cart, name='update_cart'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('account/', include('accounts.urls', namespace='accounts')),
    path('checkout/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('update-review/<int:review_id>/', views.update_review, name='update_review'),
    path('create-review/<int:product_id>/', views.create_review, name='create_review'),
    path('categories/<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('publishers/<slug:publisher_slug>', views.product_list, name='product_list_by_publisher'),
    path('contact/', views.contact, name='contact'),
    path('<int:pk>/<slug:slug>/', views.detail, name='detail'),
]

cart/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

from coupons.forms import CouponApplyForm
from store.models import Product
from .cart import Cart
from .wishlist import Wishlist


def wishlist_detail(request):
    return render(request, 'cart/wishlist.html', {'wishlist': Wishlist(request)})


def cart_detail(request):
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/cart.html', {'coupon_apply_form': coupon_apply_form, 'cart': Cart(request)})


def update_cart(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        data = json.loads(request.body)
        product_id = data['productId']
        action = data['action']
        quantity = int(data['quantity'])
        update = data['update']

        product = get_object_or_404(Product, id=product_id)
        if update == 'cart':
            cart = Cart(request)
            if action == 'add':
                cart.add(product=product, quantity=quantity)
            elif action == 'remove':
                cart.remove(product)
            elif action == 'delete':
                cart.delete(product)
        elif update == 'wishlist':
            wishlist = Wishlist(request)
            if action == 'add':
                wishlist.add(product=product)
            elif action == 'delete':
                wishlist.delete(product)
        return JsonResponse('Item was added!', safe=False)
    else:
        return redirect('/')

templates/cart/cart.html
{% extends 'main.html' %}
{% load static i18n %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">{% translate 'Главная страница' %}</a></li>
                <li class="breadcrumb-item active">{% translate 'Корзина' %}</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Cart Start -->
    <div class="cart-page">
        <div class="container-fluid">
            {% if cart %}
                <div class="row">
                    <div class="col-lg-8">
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                    <tr>
                                        <th>{% translate 'Книга' %}</th>
                                        <th>{% translate 'Цена' %}</th>
                                        <th>{% translate 'Количество' %}</th>
                                        <th>{% translate 'Всего' %}</th>
                                        <th>{% translate 'Удалить' %}</th>
                                    </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                    {% for item in cart %}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href="{{ item.product.get_absolute_url }}"><img
                                                            src="{{ item.product.base_photo.url }}" alt="Image">
                                                        <p>{{ item.product.name }}</p>
                                                    </a>
                                                </div>
                                            </td>
                                            <td>{{ item.product.price }}₽</td>
                                            <td>
                                                <div class="qty">
                                                    <button onclick="if(this.nextElementSibling.value === '1'){this.dataset.action='delete'}" data-update="cart" data-action="remove"
                                                            data-product="{{ item.product.id }}"
                                                            class="btn-minus update-cart-or-wishlist">
                                                        <i class="fa fa-minus"></i>
                                                    </button>
                                                    <input id="sst{{ item.product.id }}" type="text"
                                                           value="{{ item.quantity }}">
                                                    <button data-update="cart" data-action="add"
                                                            data-product="{{ item.product.id }}"
                                                            class="btn-plus update-cart-or-wishlist">
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </div>
                                            </td>
                                            <td>{{ item.total_price }}₽</td>
                                            <td>
                                                <button class="update-cart-or-wishlist" data-update="cart"
                                                        data-action="delete"
                                                        data-product="{{ item.product.id }}">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-page-inner">
                            <div class="row">
                                <form action="{% url 'coupons:apply' %}" method="post">
                                    <div class="col-md-12">
                                        <div class="coupon">
                                            {% csrf_token %}
                                            {{ coupon_apply_form.code }}
                                            <button>{% translate 'Применить' %}</button>
                                        </div>
                                    </div>
                                </form>

                                <div class="col-md-12">
                                    <div class="cart-summary">
                                        <div class="cart-content">
                                            <h1>{% translate 'Корзина' %}</h1>
                                            <p>Sub Total<span>{{ cart.get_total_price|floatformat:2 }}₽</span></p>
                                            {% if cart.coupon %}
                                                <p>"{{ cart.coupon.code }}" {% translate 'купон' %}</p>
                                                <p>({{ cart.coupon.discount }}% off)<span
                                                        style="color: #b61b19">- {{ cart.get_discount|floatformat:2 }}₽</span>
                                                </p>
                                            {% endif %}
                                            <p>{% translate 'Доставка' %}<span>0₽</span></p>
                                            <h2>
                                                {% translate 'Всего' %}<span>{{ cart.get_total_price_after_discount|floatformat:2 }}₽</span>
                                            </h2>
                                        </div>
                                        <form action="{% url 'orders:order_create' %}">
                                            <div class="cart-btn">
                                                <button>{% translate 'Оформление заказа' %}</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="cart-page-inner">
                    <div class="row">
                        <div class="checkout_btn_inner d-flex align-items-center">
                            <h5>{% translate 'Ваша корзина пуста. Вы пока не добавили товары в корзину' %}. <br><br><a
                                    style="color: #5a6268" href="{% url 'store:product_list' %}">{% translate 'Продолжить покупки' %}</a></h5>
                            <br>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    <!-- Cart End -->
{% endblock %}

templates/cart/wishlist.html
{% extends 'main.html' %}
{% load static i18n %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">{% translate 'Главная страница' %}</a></li>
                <li class="breadcrumb-item active">{% translate 'Cписок желании' %}</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Wishlist Start -->
    <div class="cart-page">
        <div class="container-fluid">
            {% if wishlist %}
                <div class="row" style="margin-bottom: 20px">
                    <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                    <tr>
                                        <th>{% translate 'Книга' %}</th>
                                        <th>{% translate 'Цена' %}</th>
                                        <th>{% translate 'Добавить в корзину' %}</th>
                                        <th>{% translate 'Удалить' %}</th>
                                    </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                    {% for item in wishlist %}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href="{{ item.product.get_absolute_url }}"><img
                                                            src="{{ item.product.base_photo.url }}"
                                                            alt="Image">
                                                        <p>{{ item.product.name }}</p>
                                                    </a>
                                                </div>
                                            </td>
                                            <td>{{ item.product.price }}₽</td>
                                            <td>
                                                <button data-action="add" data-update="cart"
                                                        data-product="{{ item.product.id }}"
                                                        class="btn-cart update-cart-or-wishlist">
                                                    {% translate 'Добавить в корзину' %}
                                                </button>
                                            </td>
                                            <td>
                                                <button class="update-cart-or-wishlist" data-update="wishlist"
                                                        data-action="delete"
                                                        data-product="{{ item.product.id }}">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                </div>
            {% else %}
            <div class="cart-page-inner">
                <div class="row">
                <div class="checkout_btn_inner d-flex align-items-center">
                    <h5>{% translate 'Ваш список желании пуст. Вы пока не добавили товары в список желании' %}. <br><br><a
                            style="color: #5a6268" href="{% url 'store:product_list' %}">{% translate 'Продолжить покупки' %}</a>
                    </h5>
                    <br>
                </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- Wishlist End -->
{% endblock %}